### ISSUE TITLE
SSR and API on same server? 

### ISSUE THREAD

**Issue by OskarLebuda** [hi-ogawa/vite-environment-examples#152]
Hi @hi-ogawa,  

First off, thanks so much for sharing your examples! 🙏🏻  

I’m trying to set up a Vite-based environment for my project, and I could really use some guidance. My goal is to have both Vue SSR and the API running on a single Vite server. I’m not sure if that’s even possible, though.  

Here’s a quick look at the structure I’m working with:  

```
.
├── src/
│   ├── api/
│   │   └── index.ts
│   └── app/
│       ├── entry-client.ts
│       └── entry-server.ts
├── package.json
├── vite.config.ts
└── tsconfig.json
```

### The goal:  
- The app should run on a single process, using one Vite server.  
- The API is built with `h3` as the server base.  

This is what I currently have in `src/api/index.ts`:  

```typescript
import { createApp, defineEventHandler, toNodeListener } from 'h3';
import { listen } from 'listhen';

export default () => {
  const app = createApp({ debug: true });

  app.use('/api/hello', defineEventHandler(() => {
    return 'Hello, World!';
  }));

  listen(toNodeListener(app), { port: 3000 });
};
```

I’m not entirely sure if I’m on the right track here, so I’d be super grateful for any advice or guidance you could offer! 😅  

Thanks in advance! 🙌

**Comment by hi-ogawa** [comment]
> ### The goal:
> * The app should run on a single process, using one Vite server.
> * The API is built with `h3` as the server base.

That should be possible and it's probably just a matter of integrating `h3` to Vite SSR. The simple setup would probably look like this https://stackblitz.com/edit/vitejs-vite-dxfgc2gx?file=src%2Fentry-server.ts

However, note that this is only a starting point and implementing a complete SSR setup would take a lot (e.g. production build and adapter, css on ssr, asset preload, etc...).

I don't think this is related to environment API in particular, so let me close this, but please feel free to continue the discussion if you like :smiley:

**Comment by OskarLebuda** [comment]
> > ### The goal:
> > 
> > * The app should run on a single process, using one Vite server.
> > * The API is built with `h3` as the server base.
> 
> That should be possible and it's probably just a matter of integrating `h3` to Vite SSR. The simple setup would probably look like this https://stackblitz.com/edit/vitejs-vite-dxfgc2gx?file=src%2Fentry-server.ts
> 
> However, note that this is only a starting point and implementing a complete SSR setup would take a lot (e.g. production build and adapter, css on ssr, asset preload, etc...).
> 
> I don't think this is related to environment API in particular, so let me close this, but please feel free to continue the discussion if you like 😃

Thank you so much for your help! 🙏🏻 You've completely cleared up all my doubts, and honestly, I would’ve never thought to approach it this way! XD

I really appreciate you taking the time to explain everything. Thanks again! 🙌
